pipeline:
  build_api:
    image: node:8
    commands:
      - npm install
      - npm test
  docker_publish:
    image: plugins/docker:17.12
    repo: omarvides/dockerized-api
    dockerfile: docker/Dockerfile
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]
  deploy:
    ecs:
      image: peloton/drone-ecs
      service: service1
      region: us-west-1
      family: dockerized-api
      image_name: omarvides/dockerized-api
      image_tag: latest
      port_mappings:
        - 3000 3000
      secrets: [aws_secret_access_key, aws_access_key_id]
    when:
      event: deployment
      environment: production