pipeline:
  build_api:
    image: node:8
    commands:
      - npm install
      - npm test
      - echo -n "1.0.0" > .tags
  docker_publish:
    image: plugins/docker
    repo: omarvides/dockerized-api
    dockerfile: docker/Dockerfile
    auto_tag: true
    secrets: [ docker_username, docker_password ]