version: 2
jobs:
  build-current:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install 
      - run: yarn test
  build-next:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn install 
      - run: yarn test
  build-docker:
    docker:
      - image: docker:18.09.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Building image
          command: |
            docker build -t dockerized-app -f docker/Dockerfile .
      
workflows:
  version: 2
  build_current_next:
    jobs:
      - build-current
      - build-next
      - build-docker:
          requires:
            - build-current
            - build-next